<?php
/**
 * DataForce CMS — host site entry point.
 * Generated by `vendor/bin/dataforce-install` — safe to edit.
 */

require __DIR__ . '/{{VENDOR_REL}}/autoload.php';

\DataForce\loadEnv(__DIR__ . '/{{ENV_REL}}');

$dfConfig = require __DIR__ . '/{{CONFIG_REL}}';

require __DIR__ . '/{{BOOTSTRAP_REL}}';
