<?php
/**
 * DataForce CMS — host site config.
 * Generated by `vendor/bin/dataforce-install`.
 * MUST be in .gitignore — contains DB credentials.
 */

return [
    'db' => [
        'host' => getenv('DF_DB_HOST') ?: 'localhost',
        'name' => getenv('DF_DB_NAME') ?: 'CHANGE_ME',
        'user' => getenv('DF_DB_USER') ?: 'CHANGE_ME',
        'pass' => getenv('DF_DB_PASSWORD') ?: 'CHANGE_ME',
    ],

    'project_name' => '{{PROJECT_NAME}}',
    'lang'         => 'ru',
    'langs'        => ['ru' => 'RU', 'ua' => 'Укр', 'en' => 'EN'],
    'timezone'     => 'Europe/Kyiv',

    /*
     | ------------------------------------------------------------------
     |  Upload paths
     | ------------------------------------------------------------------
     |
     |  DataForce writes/reads three kinds of upload folders:
     |    - files/      — uploaded documents (grouped by extension)
     |    - images/     — resized catalog images (.s.jpg / .b.jpg)
     |    - userfiles/  — raw user uploads (CKFinder etc.)
     |
     |  Two prefixes describe *where* those folders live:
     |
     |    fs_root  — absolute filesystem prefix used by PHP (unlink,
     |               file_exists, mkdir). Must end with a trailing slash.
     |    url_root — URL prefix used in emitted HTML (<img src>, <a href>).
     |
     |  Presets:
     |    Symfony (public/ is web root, uploads live under public/):
     |        'fs_root'  => dirname(__DIR__) . '/public/',
     |        'url_root' => '/',
     |
     |    Self-hosted vendor layout (uploads at project root):
     |        'fs_root'  => dirname(__DIR__) . '/',
     |        'url_root' => '/',
     |
     |    Legacy standalone (admin/ at project root, CMS loaded from there):
     |        'fs_root'  => '../',
     |        'url_root' => '../',
     */
    'paths' => [
        'fs_root'   => dirname(__DIR__) . '{{FS_ROOT_SUBPATH}}',
        'url_root'  => '/',
        'files'     => 'files',
        'images'    => 'images',
        'userfiles' => 'userfiles',

        // Extra directories with project-specific admin_* classes
        // (banners, docs, products, orders, ... whatever your site has).
        // Each *.php file is scanned and required_once at boot.
        'extra_models' => [
            dirname(__DIR__) . '/{{MODELS_REL}}',
        ],
    ],

    'error_display' => false, // true only in dev

    'tables' => [
        'docs_rubs'         => 'tef_drubs',
        'docs'              => 'tef_docs',
        'mail'              => 'emails',
        'tags'              => 'tags',
        'admins_groups'     => 'admins_groups',
        'admins'            => 'admins',
        'admins_menu'       => 'admins_menu',
        'admins_menu_assoc' => 'admins_menu_assoc',
        'admins_log'        => 'admins_log',
    ],

    // Project-specific tables — exposed as $TABLE_<KEY> globals.
    'extra_tables' => [
        // 'products' => 'products',
    ],
];
